// This file is generated by wombat. Do not edit.
// To regenerate, run `yarn generate_interface`.

import { BigNumberish } from 'ethers'
import { DeploymentOrAddress } from '../../types'

export interface Pool {
  ampFactor: BigNumberish
  haircutRate: BigNumberish
}

export interface Asset {
  underlyingToken: DeploymentOrAddress
  name: string
  symbol: string
}
