// We support generating multisig proposals for gnosis safe. Our scripts are located in the /scripts/multisig folder.
// At a high-level, we construct a BatchTransaction object, which tx-builder in the gnosis safe app uses.
// The BatchTransaction generated by a multisig script is saved in the /proposals folder. This can then be
// drag-and-drop into the gnosis safe UI.
// The easiest way to create a BatchTransaction object is to wrap it around an ethers.js contract. See examples in
// utils.js which provide high-level functions for the multisig scripts.
export * as files from './files'
export * as transactions from './transactions'
export * as utils from './utils'
